In [4]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
indep = sc.fit_transform(indep)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']} 



grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(indep, dep)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_

grid_prediction = grid.predict(indep)

from sklearn.metrics import r2_score
r_score = r2_score(dep,grid_prediction)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}: 0.8382747818757239

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.142005,0.003377,0.062075,0.010098,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.050402,-0.045276,-0.016737,-0.041345,-0.048491,-0.040450,0.012248,36
1,0.108334,0.013929,0.021184,0.005914,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.037227,0.042884,0.065672,0.041406,0.034393,0.044316,0.011093,32
2,0.133316,0.017644,0.022426,0.001901,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.029301,0.043379,0.060402,0.040689,0.017824,0.038319,0.014285,33
3,0.095297,0.006972,0.015312,0.001416,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,25
4,0.113243,0.007183,0.052463,0.001992,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.050517,-0.045096,-0.016601,-0.041415,-0.048600,-0.040446,0.012321,35
5,0.092222,0.003075,0.017359,0.000574,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.039041,0.040111,0.063362,0.042506,0.036594,0.044323,0.009707,31
6,0.120732,0.004212,0.023548,0.003230,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.029716,0.042770,0.059852,0.040918,0.018234,0.038298,0.013912,34
7,0.093797,0.002809,0.016489,0.000897,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.487873,0.472341,0.485102,0.475835,0.447692,0.473769,0.014239,25
8,0.112002,0.004135,0.052983,0.003475,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.360724,0.347206,0.361437,0.343682,0.333290,0.349268,0.010678,27
9,0.102878,0.005689,0.016825,0.000348,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.650669,0.616836,0.642137,0.615462,0.606497,0.626320,0.016993,19
10,0.129715,0.004314,0.023935,0.003756,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.531459,0.492180,0.518726,0.511646,0.486503,0.508103,0.016679,23
11,0.106870,0.004693,0.017344,0.001076,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.641464,0.601994,0.627339,0.628877,0.596234,0.619182,0.017199,21
12,0.113510,0.003923,0.053190,0.001934,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.360068,0.348158,0.362312,0.343255,0.332521,0.349263,0.010997,28
13,0.111718,0.007189,0.017839,0.002208,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.654011,0.612976,0.636708,0.617573,0.608877,0.626029,0.016930,20
14,0.127987,0.007544,0.023828,0.001882,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.527367,0.490754,0.520064,0.511215,0.485494,0.506979,0.016308,24
15,0.102421,0.001231,0.016416,0.000799,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.641464,0.601994,0.627339,0.628877,0.596234,0.619182,0.017199,21
16,0.124425,0.003280,0.052311,0.001933,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.833468,0.754793,0.802307,0.777257,0.783844,0.790334,0.026383,12
17,0.143289,0.015102,0.017122,0.001168,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.848655,0.774485,0.868188,0.805521,0.808550,0.821080,0.033316,8
18,0.132569,0.008251,0.022101,0.000854,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.170988,-0.021689,0.135578,0.120185,0.099719,0.100956,0.065599,30
19,0.126423,0.002012,0.016301,0.000407,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.672679,0.620927,0.730011,0.632260,0.691909,0.669557,0.039799,13
20,0.124148,0.001154,0.052286,0.001963,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.833330,0.754986,0.802746,0.777131,0.783512,0.790341,0.026356,11
21,0.140944,0.014671,0.017429,0.000766,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.848927,0.774567,0.868177,0.805541,0.808535,0.821149,0.033334,7
22,0.132101,0.003368,0.021872,0.000409,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.161027,0.099347,0.157690,0.184345,0.077914,0.136065,0.040377,29
23,0.125404,0.004102,0.016252,0.000523,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.672679,0.620927,0.730011,0.632260,0.691909,0.669557,0.039799,13
24,0.136339,0.001550,0.051916,0.000878,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.863090,0.775949,0.848369,0.801411,0.812077,0.820179,0.031655,10
25,0.214840,0.077443,0.017461,0.000829,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.851467,0.773953,0.868926,0.807826,0.814939,0.823422,0.033525,4
26,0.132499,0.001942,0.022425,0.000978,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.377095,-1.487236,-1.402559,-1.330143,-1.162566,-1.351920,0.107552,38
27,0.157410,0.013341,0.017866,0.002072,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.671545,0.618499,0.728708,0.627927,0.691027,0.667541,0.040702,15
28,0.138013,0.008497,0.053236,0.002049,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.863070,0.775993,0.848544,0.801377,0.812016,0.820200,0.031676,9
29,0.198172,0.033277,0.018082,0.001929,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.851782,0.774049,0.868717,0.807810,0.815101,0.823492,0.033486,3
30,0.142643,0.010786,0.022584,0.001004,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.075530,-1.732497,-1.358992,-1.172710,-1.199166,-1.307779,0.231079,37
31,0.152670,0.005622,0.016129,0.000090,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.671545,0.618499,0.728708,0.627927,0.691027,0.667541,0.040702,15
32,0.155835,0.011826,0.052966,0.001911,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.870252,0.781886,0.855146,0.806056,0.823614,0.827391,0.032086,2
33,0.360297,0.152107,0.016716,0.000087,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.852383,0.773067,0.868612,0.806641,0.816036,0.823348,0.033919,6
34,0.139125,0.008379,0.023090,0.002016,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.510085,-4.162603,-3.787697,-3.774905,-3.088834,-3.664825,0.355164,40
35,0.176069,0.005793,0.016349,0.000429,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.668269,0.618040,0.728704,0.627698,0.688847,0.666312,0.040560,17
36,0.149590,0.011365,0.052307,0.000889,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.870230,0.781912,0.855341,0.806008,0.823606,0.827419,0.032113,1
37,0.279443,0.058624,0.014827,0.002944,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.852350,0.773058,0.868576,0.806808,0.816178,0.823394,0.033884,5
38,0.137981,0.010019,0.021524,0.000332,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-3.433129,-4.040316,-3.681947,-3.469604,-3.179970,-3.560993,0.287840,39
39,0.153913,0.013662,0.013394,0.002712,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.668269,0.618040,0.728704,0.627698,0.688847,0.666312,0.040560,17

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 22
BMI: 18
Children: 0
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[17144.08729473]