In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
scy = StandardScaler()

X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

 Reshape before scaling 
The reason to reshape y_train and y_test into 2D arrays before scaling is because of how scikit-learn’s StandardScaler is designed:

StandardScaler expects input in the form of a 2D array with shape (n_samples, n_features).
 target variable (y_train, y_test) is a 1D Series (shape (n_samples,)).
When I pass a 1D array directly, StandardScaler doesn’t know if I mean:
multiple samples with one feature each, or one sample with multiple features.
To avoid ambiguity, scikit-learn enforces the requirement that the input must be explicitly 2D.


The difference comes down to how scikit-learn interprets the shape of your data:

X_train and X_test are already 2D arrays (shape (n_samples, n_features)), because you selected multiple columns ([['age', 'bmi', 'children','sex_male', 'smoker_yes']]).
Example: if you have 1000 rows and 5 features, the shape is (1000, 5). That’s exactly what StandardScaler expects.

y_train and y_test, on the other hand, are 1D Series (shape (n_samples,)).
Example: (1000,) — just one column of values. StandardScaler doesn’t accept this directly, because it requires a 2D input where each column is treated as a separate feature.

So:

X_train → fine, already 2D.

y_train → needs reshaping into (n_samples, 1) so that StandardScaler knows it’s feature column."""

In [8]:


#.reshape(-1, 1) converts your 1D array into a 2D array with one column (one feature).one -1 tells NumPy to infer the number of rows automatically.

y_train = scy.fit_transform(y_train.values.reshape(-1, 1))
y_test = scy.transform(y_test.values.reshape(-1, 1))
y_train

array([[-9.74704706e-01],
       [ 2.43595227e+00],
       [-3.54990167e-01],
       [-7.40302357e-01],
       [-7.72992119e-01],
       [-3.56105745e-01],
       [-3.12405716e-01],
       [-4.57593414e-01],
       [-1.32221217e-01],
       [-7.93946645e-01],
       [-9.29662595e-01],
       [-8.53316663e-01],
       [-7.77169102e-01],
       [-4.74957055e-01],
       [ 1.80292292e+00],
       [-1.77344443e-02],
       [-5.06614701e-01],
       [ 1.10861258e+00],
       [-1.18018584e-01],
       [-9.62233850e-01],
       [-1.95774021e-01],
       [-1.98220356e-01],
       [-7.48375214e-01],
       [-9.73871211e-01],
       [ 2.62922835e+00],
       [-4.66763102e-01],
       [ 1.28665821e+00],
       [-8.07799710e-01],
       [ 9.62739634e-01],
       [-6.47487283e-01],
       [-1.09681055e-01],
       [ 3.90197468e-01],
       [ 1.75728577e+00],
       [-3.02271094e-01],
       [-4.33454326e-01],
       [-9.67185594e-01],
       [-7.53146992e-01],
       [-4.09292284e-01],
       [-9.31667258e-01],
       [-2.77883406e-01],
       [-9.64461328e-01],
       [-8.24880173e-01],
       [ 2.28231646e+00],
       [-5.82978348e-01],
       [-4.97047955e-01],
       [-7.74310909e-01],
       [ 6.81971664e-01],
       [-2.31166986e-01],
       [-2.88712613e-02],
       [-6.94339340e-01],
       [-5.93716072e-01],
       [-6.96002069e-01],
       [-9.82143048e-01],
       [-3.75359116e-01],
       [ 7.22722023e-01],
       [-6.78952508e-01],
       [ 2.79836349e+00],
       [-2.69200358e-01],
       [-5.38498784e-01],
       [-8.54190645e-01],
       [-5.73620869e-01],
       [ 2.25005714e+00],
       [-9.50653096e-01],
       [-1.18533629e-01],
       [-3.64203046e-01],
       [-3.90884297e-01],
       [-9.24310059e-01],
       [-1.01571536e-01],
       [-7.70132870e-03],
       [ 1.89989459e+00],
       [-8.57665031e-02],
       [-4.81987390e-01],
       [ 2.16193384e-02],
       [ 9.44803016e-02],
       [ 1.96102217e+00],
       [-4.32940208e-01],
       [-1.51087271e-01],
       [ 6.19947084e-01],
       [-8.03490057e-01],
       [ 1.90074214e+00],
       [-7.16456379e-01],
       [ 5.25776211e-01],
       [ 4.79714131e-01],
       [-7.39618565e-01],
       [-2.18182994e-01],
       [-2.16556308e-01],
       [-6.55159336e-01],
       [-9.45518567e-01],
       [-1.01494101e+00],
       [-9.73234152e-01],
       [-8.38866133e-01],
       [-9.65437799e-01],
       [ 2.47093937e-02],
       [-8.40008668e-01],
       [-4.90070425e-01],
       [-3.46195228e-01],
       [-1.18072338e-01],
       [-5.55844249e-01],
       [-4.91509347e-02],
       [-9.26098295e-01],
       [-3.35521647e-01],
       [-6.77111094e-01],
       [-4.83887390e-01],
       [-6.55756760e-02],
       [-1.09822142e-01],
       [ 6.43898964e-01],
       [-6.30051181e-03],
       [-4.29586120e-01],
       [-4.97807955e-01],
       [ 1.12178908e+00],
       [-6.56198591e-01],
       [-1.78134747e-01],
       [-5.13003360e-01],
       [-6.66268190e-01],
       [ 7.39948986e-01],
       [-2.05220462e-01],
       [-2.96554030e-01],
       [-1.89869793e-02],
       [-2.42815388e-01],
       [-6.78214861e-01],
       [-8.17096355e-01],
       [-6.82033710e-01],
       [-5.70125503e-01],
       [-9.67721070e-01],
       [-4.98900591e-01],
       [-8.41056226e-01],
       [-6.66145249e-01],
       [-7.63846317e-02],
       [-8.11182516e-01],
       [-7.93181600e-01],
       [-9.24153995e-01],
       [-9.17141307e-01],
       [-7.44079645e-01],
       [ 4.24845783e-01],
       [ 7.83531236e-01],
       [ 2.01539868e+00],
       [-1.53369071e-02],
       [-2.76396347e-01],
       [ 2.64794603e+00],
       [-9.73656471e-01],
       [-5.98705252e-02],
       [-9.75248236e-01],
       [-6.67355080e-01],
       [ 3.41968619e-01],
       [-2.56638982e-01],
       [-6.69516337e-01],
       [ 4.20917821e-02],
       [-2.60085554e-01],
       [ 2.23944868e+00],
       [ 1.44124386e+00],
       [-5.94665361e-01],
       [-9.25926061e-02],
       [ 5.33723474e-01],
       [-9.73889412e-01],
       [-3.83735955e-01],
       [-7.73943850e-01],
       [-9.74730589e-01],
       [ 9.75801653e-01],
       [ 1.70708668e+00],
       [ 6.46903604e-01],
       [ 1.03262035e-01],
       [-5.20763196e-01],
       [ 9.52628007e-01],
       [ 9.92933927e-01],
       [-4.14535285e-01],
       [ 3.42039681e-01],
       [ 2.25441855e+00],
       [-7.44636771e-01],
       [ 9.02997719e-01],
       [-3.84002934e-01],
       [ 9.64653074e-01],
       [ 3.74274788e-01],
       [-4.36854920e-02],
       [-3.02606422e-01],
       [ 3.09613943e-01],
       [ 7.66173663e-03],
       [ 1.86388600e+00],
       [-9.24857706e-01],
       [-2.27488090e-01],
       [-1.46139543e-01],
       [-9.25483589e-01],
       [-5.77771661e-01],
       [ 9.93234231e-01],
       [-9.68559306e-01],
       [-9.02665292e-01],
       [-1.79699453e-01],
       [ 4.24300493e-04],
       [-5.48839233e-01],
       [-1.01705042e+00],
       [ 3.96809816e+00],
       [-9.44414268e-01],
       [-1.82913029e-01],
       [ 5.95797566e-01],
       [-9.01784894e-01],
       [-7.28063084e-01],
       [ 1.08798127e+00],
       [ 2.80777369e-01],
       [-5.93273528e-01],
       [ 2.83205992e+00],
       [ 1.60561498e+00],
       [-1.25282152e-01],
       [-9.57383122e-01],
       [-2.76937706e-01],
       [ 2.53951654e-01],
       [-6.10936954e-01],
       [-9.40444390e-01],
       [-4.84113590e-01],
       [ 1.58125779e-01],
       [-4.65417401e-01],
       [-1.36963507e-01],
       [-3.42213768e-01],
       [-4.16518481e-02],
       [-7.62102575e-01],
       [-9.74776505e-01],
       [-9.83747754e-01],
       [ 1.83395228e+00],
       [-5.81112736e-01],
       [ 6.28544671e-02],
       [-8.28187934e-01],
       [ 2.41415837e+00],
       [-9.63990740e-01],
       [-4.65341925e-01],
       [-3.59473926e-01],
       [-1.50280889e-01],
       [-4.56725708e-01],
       [-9.65673093e-01],
       [-5.36510040e-01],
       [-1.87421967e-01],
       [-3.89338596e-01],
       [-9.07437116e-01],
       [ 4.66364678e-01],
       [-4.77591699e-02],
       [-1.48709124e-01],
       [-9.29460242e-01],
       [-7.77901929e-01],
       [-4.30323222e-02],
       [-9.44043273e-01],
       [-8.18189999e-01],
       [-6.67017886e-01],
       [ 2.46053226e-02],
       [-9.71081253e-01],
       [-3.34841634e-01],
       [-8.74910342e-01],
       [-9.16997236e-01],
       [-5.01805526e-01],
       [-7.67149444e-01],
       [-8.82709488e-01],
       [-4.30942012e-02],
       [-3.68671599e-01],
       [ 2.94189344e+00],
       [-2.58356142e-01],
       [ 2.12503361e+00],
       [ 2.01426740e-01],
       [ 6.76549330e-02],
       [-5.38987019e-01],
       [-6.94598163e-01],
       [-8.24796284e-01],
       [-3.76594592e-01],
       [ 1.77063115e-01],
       [-7.38312784e-01],
       [-8.82564194e-01],
       [-8.66779601e-01],
       [-2.28711620e-01],
       [-7.93654880e-01],
       [ 5.58291290e-03],
       [-3.52940662e-01],
       [-5.53374371e-01],
       [-7.65548560e-02],
       [ 1.17643604e+00],
       [-1.10682731e-01],
       [-1.42556259e-01],
       [ 4.99581295e-01],
       [-9.09280828e-01],
       [-8.65404612e-01],
       [-4.65899572e-01],
       [-1.01539395e+00],
       [-5.69119438e-01],
       [-1.01585983e+00],
       [-5.88575944e-01],
       [ 5.94922822e-01],
       [-4.24368650e-01],
       [-7.43784169e-01],
       [-7.70722275e-01],
       [ 2.26040444e-02],
       [-8.15718335e-01],
       [-9.42054978e-01],
       [-9.73826505e-01],
       [-3.85613344e-01],
       [-3.97431822e-01],
       [-8.78823830e-01],
       [-6.29579918e-01],
       [-6.98123132e-01],
       [-3.90716967e-01],
       [ 2.41538385e+00],
       [-7.21137912e-01],
       [-1.00520234e+00],
       [-1.68222067e-01],
       [-5.46076414e-01],
       [-5.07275619e-01],
       [ 6.85049468e-01],
       [-3.31194880e-01],
       [-7.99398765e-01],
       [-7.60777687e-01],
       [ 4.05499811e-01],
       [ 1.80571472e+00],
       [-2.61420625e-02],
       [-5.02874066e-01],
       [-7.83968709e-01],
       [-9.74430034e-01],
       [ 1.87962858e-01],
       [-7.78225052e-01],
       [-8.51564026e-01],
       [-8.43564076e-01],
       [ 4.03402789e-01],
       [ 1.71240884e-01],
       [ 2.87069079e+00],
       [ 1.98408470e+00],
       [ 1.17331041e+00],
       [-9.52878086e-01],
       [ 3.66539210e-01],
       [-1.53331260e-01],
       [-5.67304313e-01],
       [-5.74020607e-01],
       [-1.00508469e+00],
       [-4.25022768e-01],
       [ 2.79240000e+00],
       [ 3.56695485e-01],
       [-9.40987919e-01],
       [ 2.74393982e-02],
       [ 2.12817844e+00],
       [-6.49117025e-01],
       [ 4.76305749e-01],
       [ 9.76160886e-01],
       [-4.56875754e-01],
       [-3.83791837e-01],
       [-5.23878401e-01],
       [-8.70727105e-01],
       [-8.53753266e-02],
       [ 1.20054267e+00],
       [-8.25469767e-01],
       [-1.06335510e-01],
       [ 9.28267932e-02],
       [ 2.26801727e-01],
       [ 1.05322524e-01],
       [ 4.33423016e-01],
       [ 4.39264921e-01],
       [-5.40815314e-01],
       [-3.26260000e-01],
       [ 2.60330559e+00],
       [-2.36935438e-01],
       [-3.65217515e-01],
       [-1.59534720e-01],
       [-4.90274860e-01],
       [-5.88421260e-01],
       [-7.17480997e-01],
       [ 1.01087138e+00],
       [ 4.32346376e-01],
       [ 5.08358319e-01],
       [-1.39653554e-01],
       [-1.00686116e+00],
       [-6.87757367e-01],
       [-9.31041376e-01],
       [-2.15327810e-01],
       [-4.56129297e-01],
       [-5.06540008e-01],
       [ 2.07102890e+00],
       [-2.77384583e-01],
       [-9.82819519e-01],
       [ 9.59640797e-01],
       [-1.60300196e-01],
       [-6.68434978e-01],
       [-4.17887927e-02],
       [-2.29827096e-01],
       [-3.15473456e-01],
       [-5.47785115e-01],
       [-6.88486779e-01],
       [-9.53059262e-01],
       [ 3.08415931e+00],
       [ 1.06325389e-01],
       [-5.44251163e-02],
       [-6.39358319e-01],
       [-8.09013603e-01],
       [-1.75013858e-01],
       [ 8.41908000e-02],
       [ 2.27718869e-01],
       [-2.33334329e-01],
       [-1.01576925e+00],
       [-9.94227332e-01],
       [-4.15169403e-01],
       [-8.24828408e-01],
       [-7.07466950e-01],
       [-2.48882913e-01],
       [-2.10127730e-02],
       [ 2.51966249e-01],
       [-9.31309611e-01],
       [-7.44865777e-01],
       [-7.34991256e-01],
       [-4.32531190e-01],
       [ 1.23452954e+00],
       [-3.07576265e-01],
       [-5.52283284e-02],
       [ 4.14358427e-01],
       [ 2.59119901e+00],
       [-8.36066479e-01],
       [ 2.64596579e+00],
       [-4.47259051e-02],
       [-4.27795532e-01],
       [-6.65776426e-01],
       [-7.66976503e-01],
       [ 2.02632676e+00],
       [-1.67139714e-01],
       [-2.73208971e-01],
       [-6.67987920e-01],
       [-9.33915460e-01],
       [ 2.48054294e-01],
       [ 6.46238249e-01],
       [-8.43916091e-01],
       [-5.73808524e-01],
       [-1.01353042e+00],
       [-1.98591939e-01],
       [-1.93837448e-01],
       [-7.53381110e-01],
       [-6.89458137e-01],
       [-8.74315392e-02],
       [ 2.77796980e-01],
       [ 1.07711272e-01],
       [ 1.95097590e+00],
       [ 2.81452806e-02],
       [-4.58016931e-01],
       [-1.73994628e-01],
       [-3.86666285e-01],
       [-4.29127297e-01],
       [ 1.11005585e-01],
       [ 3.17105443e-01],
       [ 2.27212060e+00],
       [-2.77177490e-01],
       [-3.53302021e-01],
       [ 1.86281904e+00],
       [-8.89152138e-01],
       [-7.85490068e-01],
       [-7.83835814e-01],
       [-4.06590473e-01],
       [ 2.83733576e+00],
       [ 2.25046914e+00],
       [ 1.83167951e+00],
       [-1.50236183e-01],
       [ 2.50716728e+00],
       [ 3.00763763e+00],
       [ 6.94585181e-01],
       [ 3.30513603e-01],
       [-8.02283404e-01],
       [ 1.33138737e+00],
       [-6.88577367e-01],
       [-2.43240094e-01],
       [-9.29550830e-01],
       [ 2.45225085e+00],
       [-4.14405574e-02],
       [-5.02464938e-01],
       [-8.81652507e-02],
       [-7.25087709e-01],
       [-3.25882116e-01],
       [ 1.94551437e+00],
       [-5.57776479e-01],
       [ 2.80369993e-01],
       [-2.84382281e-01],
       [-9.56938687e-01],
       [ 2.30898841e+00],
       [ 1.11173232e-01],
       [-7.39406800e-01],
       [-2.97283442e-01],
       [ 4.62965634e-01],
       [-5.05986466e-01],
       [-8.93191326e-01],
       [-9.41019684e-01],
       [-3.53155157e-01],
       [ 7.48721785e-01],
       [-9.04029909e-01],
       [-1.25315682e-01],
       [ 9.70353440e-01],
       [ 2.45229917e+00],
       [-1.82994328e-01],
       [-9.03817556e-01],
       [-7.98473966e-01],
       [ 6.87351262e-01],
       [-3.08986854e-01],
       [-9.23974617e-01],
       [ 2.59632208e+00],
       [-4.89221195e-01],
       [ 2.66634590e+00],
       [-7.33957084e-01],
       [-9.74316925e-02],
       [-8.84369793e-01],
       [ 1.93674903e+00],
       [-8.17304819e-01],
       [-2.86873741e-01],
       [-2.59523383e-01],
       [-4.15208226e-01],
       [ 1.33831122e+00],
       [-1.56514131e-01],
       [ 2.49412123e-01],
       [ 1.43252294e+00],
       [ 2.79414338e+00],
       [-7.15356379e-01],
       [ 7.30935202e-01],
       [-9.36096185e-02],
       [-7.62139883e-01],
       [-6.05890241e-01],
       [-1.87005903e-01],
       [-2.61961475e-01],
       [-7.34246233e-01],
       [-2.82474452e-01],
       [-9.74172975e-01],
       [-7.18710565e-01],
       [-2.05996933e-01],
       [-8.66207066e-01],
       [-1.79803267e-02],
       [ 3.84534534e+00],
       [-3.15142098e-01],
       [ 3.33707730e-01],
       [ 1.74455947e+00],
       [-2.38097148e-01],
       [-1.84395179e-01],
       [-1.58593543e-01],
       [-9.02018233e-01],
       [ 7.21253267e-01],
       [ 8.30551461e-02],
       [ 5.63667510e-01],
       [-8.09168466e-01],
       [-9.38860712e-01],
       [ 2.13341048e+00],
       [-4.95710409e-01],
       [ 7.68497012e-01],
       [ 9.28361407e-01],
       [ 2.19288733e+00],
       [-9.44605127e-01],
       [ 1.18321384e+00],
       [-9.38668593e-02],
       [-5.79650383e-01],
       [ 2.16442478e+00],
       [ 5.46465231e-01],
       [-3.89221580e-01],
       [ 2.08983520e+00],
       [-2.97756510e-01],
       [-6.20774023e-02],
       [-6.71074517e-01],
       [ 5.77775996e-01],
       [-5.72557496e-01],
       [ 6.33838789e-02],
       [ 7.13945737e-02],
       [ 5.33561620e-01],
       [-9.25148295e-01],
       [-7.84720203e-01],
       [ 7.78099375e-01],
       [-7.43231545e-01],
       [ 4.96951633e-02],
       [-1.02175066e-01],
       [ 3.96991327e-02],
       [-3.27848235e-01],
       [-7.09664623e-01],
       [ 1.13106355e-01],
       [ 6.55138519e-01],
       [ 8.59128718e-01],
       [-6.28815677e-01],
       [ 1.82258364e+00],
       [ 1.16700737e+00],
       [-3.88233344e-01],
       [-5.20662472e-01],
       [-4.66668984e-01],
       [-9.05651234e-01],
       [-6.06342742e-01],
       [ 5.86366250e-02],
       [ 2.06061177e+00],
       [-2.76144176e-01],
       [-4.24252180e-01],
       [-8.82698312e-01],
       [-1.73305622e-01],
       [-9.67084012e-01],
       [-2.52352147e-01],
       [ 2.13487502e-02],
       [ 5.97946445e-02],
       [-5.99166415e-01],
       [-1.23926676e-01],
       [-6.75936545e-01],
       [-8.42780391e-02],
       [-6.05061409e-01],
       [-6.36729178e-01],
       [-7.08928931e-01],
       [-9.53278086e-01],
       [-1.47630821e-01],
       [-9.21497194e-01],
       [-9.85703869e-04],
       [-6.10366332e-01],
       [-3.36145685e-02],
       [-5.32314695e-01],
       [-5.05824113e-01],
       [ 3.55455628e+00],
       [-7.36357253e-01],
       [-7.85198032e-01],
       [-3.03745982e-01],
       [-6.48352725e-01],
       [-1.56731698e-01],
       [-2.78281155e-01],
       [-1.66983163e-01],
       [-3.41644174e-01],
       [-3.90249003e-01],
       [ 1.56425554e+00],
       [-4.13545467e-01],
       [-3.65157697e-01],
       [ 1.37051723e+00],
       [-9.00659012e-01],
       [-5.15582049e-01],
       [ 2.99711029e+00],
       [-2.57414627e-01],
       [-7.53567276e-01],
       [-8.39062744e-02],
       [-7.12533878e-01],
       [ 2.90516916e+00],
       [ 2.25029175e+00],
       [ 7.32854648e-01],
       [-1.00681410e+00],
       [-2.75981053e-01],
       [ 6.94911826e-01],
       [ 5.41762171e-01],
       [-1.83908400e-01],
       [-7.28831264e-01],
       [-9.09202593e-01],
       [-1.50010301e-01],
       [-8.10808648e-01],
       [-6.86430613e-01],
       [-9.14668264e-01],
       [ 6.00637483e-01],
       [ 8.60619924e-01],
       [ 2.43850387e+00],
       [-3.38024453e-01],
       [ 2.04559072e-01],
       [-4.17031214e-01],
       [ 2.88883061e+00],
       [-6.27111208e-01],
       [-8.31868967e-01],
       [-4.23299692e-02],
       [-5.77618720e-01],
       [ 2.79095984e+00],
       [-1.55090069e-01],
       [-4.75691808e-01],
       [-9.65787947e-01],
       [-9.03402939e-01],
       [-7.10221872e-01],
       [-1.09665672e-01],
       [ 5.57035275e-01],
       [-4.06579296e-01],
       [-8.33330055e-01],
       [ 3.82972584e-01],
       [ 6.72351857e-01],
       [-1.42449741e-01],
       [ 4.92331542e-01],
       [-2.17811196e-01],
       [ 2.33450953e+00],
       [ 1.03014529e+00],
       [ 2.17133850e+00],
       [-8.54347116e-01],
       [-3.78089945e-01],
       [-5.65591325e-01],
       [-9.58311357e-01],
       [-8.81848900e-01],
       [ 4.93004564e-01],
       [-7.06108126e-01],
       [-5.97200101e-01],
       [-6.95337148e-01],
       [-1.00523763e+00],
       [ 8.82327008e-01],
       [ 3.52671518e-02],
       [-3.91154885e-01],
       [-8.43529959e-01],
       [ 2.09383837e-01],
       [-5.15250284e-01],
       [-9.65767211e-01],
       [-2.53676481e-01],
       [ 5.34722318e-02],
       [ 9.34626405e-01],
       [ 1.83583009e+00],
       [ 1.02541767e-01],
       [-5.53361248e-01],
       [ 1.80936335e-02],
       [ 4.98090309e-01],
       [ 1.49233459e-01],
       [ 4.79596224e-01],
       [ 5.38163032e-01],
       [ 1.10046872e+00],
       [ 5.26760545e-01],
       [-6.68057331e-01],
       [ 7.48231416e-01],
       [-1.00863119e-01],
       [-9.31141964e-01],
       [-1.35412839e-01],
       [ 5.75127811e-01],
       [-9.67911070e-01],
       [-8.85093120e-01],
       [-1.01582101e+00],
       [-5.87352720e-01],
       [ 1.81798723e+00],
       [-8.12579046e-01],
       [-8.83491863e-02],
       [-6.57212019e-01],
       [-7.73569847e-02],
       [ 2.97875094e-01],
       [-3.04412046e-01],
       [ 2.46067011e+00],
       [ 7.89142706e-01],
       [-5.44065361e-01],
       [ 9.96775150e-01],
       [-2.90618350e-01],
       [-5.71218478e-01],
       [-5.86916837e-01],
       [-2.35521185e-01],
       [-1.79823262e-01],
       [-3.00840505e-01],
       [-6.35452085e-01],
       [-1.06387275e-01],
       [-7.03148058e-01],
       [-8.79930301e-01],
       [ 6.64051696e-01],
       [-8.98447315e-01],
       [-6.93065222e-01],
       [-3.98667345e-01],
       [-1.40134477e-01],
       [ 9.46144192e-02],
       [-9.25706936e-01],
       [-9.67642835e-01],
       [-2.14792677e-01],
       [ 2.81405747e-02],
       [-5.88489495e-01],
       [-4.38747949e-01],
       [ 1.19171519e+00],
       [ 2.44275913e+00],
       [ 7.30266898e-02],
       [ 5.53111536e-01],
       [-9.56056334e-01],
       [ 1.03216339e+00],
       [ 9.09804499e-01],
       [ 1.35828695e+00],
       [ 1.21841648e+00],
       [-1.00989501e-01],
       [-4.82168690e-01],
       [-3.67306893e-01],
       [-9.28615536e-01],
       [-8.52798665e-01],
       [-3.81784414e-01],
       [-1.33053164e-01],
       [-1.18700349e-01],
       [-4.76179184e-01],
       [ 1.06140128e+00],
       [-8.44424076e-01],
       [ 2.67416230e-01],
       [ 2.89062502e+00],
       [-1.97332607e-01],
       [ 9.96760373e-01],
       [-3.13618162e-01],
       [ 3.02554510e+00],
       [ 1.09784229e+00],
       [-5.70860831e-01],
       [-2.89672692e-01],
       [ 1.29821522e+00],
       [ 2.35319208e+00],
       [ 2.01204289e+00],
       [-7.15237183e-01],
       [ 6.16359017e-01],
       [-7.60668275e-01],
       [ 1.25289593e+00],
       [ 1.24167608e+00],

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']} 



grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_

grid_prediction = grid.predict(X_test)

from sklearn.metrics import r2_score
r_score = r2_score(y_test,grid_prediction)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.8818140952905176

In [12]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.102039,0.007152,0.010308,0.000938,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",8.164633e-01,8.040041e-01,8.640516e-01,8.322548e-01,7.450273e-01,8.123602e-01,3.921270e-02,1
1,0.353507,0.078008,0.004274,0.000200,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",8.041773e-01,7.850967e-01,8.602267e-01,8.174638e-01,7.609121e-01,8.055753e-01,3.329936e-02,4
2,0.067381,0.002834,0.013830,0.006560,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.119323e+03,-4.458988e+03,-3.041481e+03,-3.533611e+03,-2.743267e+03,-3.379334e+03,5.959506e+02,32
3,0.350189,0.036651,0.004618,0.000197,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",6.540292e-01,6.209861e-01,6.330632e-01,6.033335e-01,5.969204e-01,6.216665e-01,2.062114e-02,21
4,0.119841,0.023362,0.012116,0.000737,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",8.165165e-01,8.037780e-01,8.639829e-01,8.322501e-01,7.450087e-01,8.123072e-01,3.921136e-02,2
5,0.442488,0.093103,0.004225,0.000116,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",8.041550e-01,7.854628e-01,8.602929e-01,8.177500e-01,7.609739e-01,8.057269e-01,3.328044e-02,3
6,0.067734,0.002983,0.012227,0.000442,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-2.106276e+03,-3.752820e+03,-3.119519e+03,-3.532598e+03,-2.657935e+03,-3.033830e+03,5.957704e+02,31
7,0.337934,0.020498,0.004520,0.000125,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",6.540292e-01,6.209861e-01,6.330632e-01,6.033335e-01,5.969204e-01,6.216665e-01,2.062114e-02,21
8,0.465714,0.041521,0.012078,0.000385,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",7.945466e-01,7.129582e-01,8.082692e-01,8.007991e-01,6.925698e-01,7.618286e-01,4.884873e-02,13
9,3.685128,1.097217,0.004318,0.000152,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",8.041580e-01,7.830147e-01,8.597524e-01,8.158259e-01,7.609834e-01,8.047469e-01,3.327530e-02,7
10,0.070542,0.004386,0.012321,0.000499,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.682662e+05,-3.840028e+05,-3.057685e+05,-3.582869e+05,-2.468880e+05,-3.326425e+05,5.028043e+04,34
11,2.485382,0.180088,0.004444,0.000095,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",6.540332e-01,6.209538e-01,6.327876e-01,6.032624e-01,5.970678e-01,6.216210e-01,2.056982e-02,23
12,0.463468,0.054031,0.012092,0.000355,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",7.947437e-01,7.115481e-01,8.078084e-01,8.007900e-01,6.918544e-01,7.613489e-01,4.927253e-02,14
13,3.395673,0.764227,0.004340,0.000217,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",8.040923e-01,7.831239e-01,8.597587e-01,8.159375e-01,7.609531e-01,8.047731e-01,3.327883e-02,6
14,0.067270,0.002893,0.011640,0.000076,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-2.237858e+05,-4.422581e+05,-2.963738e+05,-3.581849e+05,-2.730697e+05,-3.187345e+05,7.538561e+04,33
15,2.507014,0.175788,0.004497,0.000142,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",6.540332e-01,6.209538e-01,6.327876e-01,6.032624e-01,5.970678e-01,6.216210e-01,2.056982e-02,23
16,2.893221,0.406928,0.013296,0.000367,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",7.621544e-01,3.583427e-01,6.860459e-01,6.668311e-01,4.585918e-01,5.863932e-01,1.520744e-01,25
17,32.060846,6.511437,0.004274,0.000087,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",8.043021e-01,7.827261e-01,8.596381e-01,8.158066e-01,7.610214e-01,8.046989e-01,3.326374e-02,9
18,0.070030,0.004507,0.011511,0.000066,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.627661e+07,-3.228607e+07,-3.396136e+07,-3.470583e+07,-2.593406e+07,-3.263279e+07,3.587009e+06,36
19,21.947318,1.244568,0.004448,0.000116,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",6.542046e-01,6.211833e-01,6.325887e-01,6.029886e-01,5.974207e-01,6.216772e-01,2.056684e-02,19
20,2.847438,0.310151,0.013448,0.000395,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",7.634286e-01,3.491384e-01,6.857344e-01,6.670807e-01,4.569913e-01,5.844747e-01,1.553943e-01,26
21,32.978053,7.709165,0.004254,0.000107,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",8.041746e-01,7.824190e-01,8.597798e-01,8.159876e-01,7.609845e-01,8.046691e-01,3.337349e-02,12
22,0.066115,0.003512,0.011443,0.000292,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.251649e+07,-3.436685e+07,-3.464424e+07,-3.469524e+07,-2.693482e+07,-3.063153e+07,5.021707e+06,35
23,22.636681,1.282860,0.004899,0.000851,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",6.542046e-01,6.211833e-01,6.325887e-01,6.029886e-01,5.974207e-01,6.216772e-01,2.056684e-02,19
24,5.601462,0.192667,0.015648,0.001519,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",7.289792e-01,1.956377e-01,5.633770e-01,5.873714e-01,3.456672e-01,4.842065e-01,1.893619e-01,28
25,66.000320,9.583002,0.004403,0.000131,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",8.043584e-01,7.828630e-01,8.596823e-01,8.155235e-01,7.609882e-01,8.046831e-01,3.325023e-02,10
26,0.072863,0.001747,0.011817,0.000435,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-9.547201e+07,-1.291457e+08,-1.358462e+08,-1.565415e+08,-9.202100e+07,-1.218053e+08,2.465027e+07,37
27,44.092875,7.262516,0.004521,0.000179,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",6.542153e-01,6.215724e-01,6.329801e-01,6.029644e-01,5.974735e-01,6.218411e-01,2.060265e-02,15
28,5.905557,0.717465,0.014568,0.000811,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",7.309884e-01,2.014539e-01,5.597450e-01,5.873360e-01,3.453541e-01,4.849755e-01,1.878665e-01,27
29,64.905867,13.085142,0.004322,0.000109,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",8.042591e-01,7.824942e-01,8.599257e-01,8.158994e-01,7.610801e-01,8.047317e-01,3.338049e-02,8
30,0.072924,0.003067,0.012533,0.001498,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-9.006549e+07,-1.360876e+08,-1.385784e+08,-1.564946e+08,-1.064694e+08,-1.255391e+08,2.392307e+07,38
31,41.914954,5.479387,0.004488,0.000107,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",6.542153e-01,6.215724e-01,6.329801e-01,6.029644e-01,5.974735e-01,6.218411e-01,2.060265e-02,15
32,9.073367,0.830171,0.015676,0.003438,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",7.003567e-01,1.805175e-01,4.535508e-01,5.497773e-01,2.789197e-01,4.326244e-01,1.860249e-01,30
33,90.929952,12.284545,0.004270,0.000113,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",8.044073e-01,7.829264e-01,8.598502e-01,8.152787e-01,7.609388e-01,8.046803e-01,3.329467e-02,11
34,0.073077,0.004104,0.012244,0.000543,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.148115e+08,-2.905788e+08,-3.056545e+08,-3.522157e+08,-1.910702e+08,-2.708661e+08,5.954173e+07,39
35,68.532802,4.890037,0.004577,0.000143,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",6.540408e-01,6.213639e-01,6.334149e-01,6.026396e-01,5.976531e-01,6.218225e-01,2.061436e-02,17
36,8.710742,1.081529,0.014089,0.000505,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",7.052522e-01,1.862302e-01,4.497210e-01,5.500758e-01,2.754017e-01,4.333362e-01,1.864616e-01,29
37,78.946529,7.975863,0.003479,0.000775,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",8.042638e-01,7.828772e-01,8.599478e-01,8.160293e-01,7.611536e-01,8.048543e-01,3.332647e-02,5
38,0.073687,0.006250,0.011327,0.000159,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.026470e+08,-3.005740e+08,-2.805319e+08,-3.521102e+08,-2.350068e+08,-2.741740e+08,5.188761e+07,40
39,59.650913,3.585915,0.002581,0.000430,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",6.540408e-01,6.213639e-01,6.334149e-01,6.026396e-01,5.976531e-01,6.218225e-01,2.061436e-02,17

In [13]:
import pickle
filename="insurance_pre.sav"
pickle.dump(grid,open(filename,'wb'))

In [14]:
preinput = sc.transform([[25,19,1,0,1]])
preinput

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.03919296, -1.88849237, -0.0755796 , -0.98885138,  2.00280702]])

In [15]:
loaded_model=pickle.load(open("insurance_pre.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([0.60743072])

In [19]:
preoutput = scy.inverse_transform([result])
preoutput

array([[20315.11685188]])